version: '3.1'

services:
  db:
    platform: linux/x86_64
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234 # Tutaj wprowadź swoje hasło
      MYSQL_DATABASE: lifter    # Nazwa bazy danych do utworzenia
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - "./db:/var/lib/mysql"
